import { Data, IProductInput, IUserInput } from '@/types'
import { toSlug } from './utils'
import bcrypt from 'bcryptjs'

const users: IUserInput[] = [
  {
    name: 'John',
    email: 'admin@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'Admin',
    address: {
      fullName: 'John Doe',
      street: '111 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jane',
    email: 'jane@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jane Harris',
      street: '222 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '1002',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Jack',
    email: 'jack@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jack Ryan',
      street: '333 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '1003',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Sarah',
    email: 'sarah@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Sarah Smith',
      street: '444 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '1005',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Michael',
    email: 'michael@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'John Alexander',
      street: '555 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '1006',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Emily',
    email: 'emily@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Emily Johnson',
      street: '666 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Alice',
    email: 'alice@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Alice Cooper',
      street: '777 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10007',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Tom',
    email: 'tom@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Tom Hanks',
      street: '888 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10008',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Linda',
    email: 'linda@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Linda Holmes',
      street: '999 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10009',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'George',
    email: 'george@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'George Smith',
      street: '101 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10010',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'Jessica',
    email: 'jessica@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Jessica Brown',
      street: '102 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10011',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Chris',
    email: 'chris@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Chris Evans',
      street: '103 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10012',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
  {
    name: 'Samantha',
    email: 'samantha@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Samantha Wilson',
      street: '104 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10013',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Stripe',
    emailVerified: false,
  },
  {
    name: 'David',
    email: 'david@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'David Lee',
      street: '105 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10014',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'Cash On Delivery',
    emailVerified: false,
  },
  {
    name: 'Anna',
    email: 'anna@example.com',
    password: bcrypt.hashSync('123456', 5),
    role: 'User',
    address: {
      fullName: 'Anna Smith',
      street: '106 First Ave',
      city: 'New York',
      state: 'NY',
      postalCode: '10015',
      country: 'USA',
      phone: '123-456-7890',
    },
    paymentMethod: 'PayPal',
    emailVerified: false,
  },
]

const products: IProductInput[] = [
  // Product with Variants
  {
    name: 'Nike Mens Slim-fit Long-Sleeve T-Shirt',
    slug: toSlug('Nike Mens Slim-fit Long-Sleeve T-Shirt'),
    category: 'T-Shirts',
    images: ['/images/p11-1.jpg', '/images/p11-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 21.8,
    listPrice: 0,
    brand: 'Nike',
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    numSales: 9,
    countInStock: 0, // Stock handled by variants
    description:
      'Made with chemicals safer for human health and the environment',
    size: '', 
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'NMSLT-GRN-S',
        images: ['/images/p11-1.jpg'],
        price: 21.8,
        countInStock: 5,
        color: 'Green',
        size: 'S',
      },
      {
        sku: 'NMSLT-RED-M',
        images: ['/images/p11-2.jpg'],
        price: 21.8,
        countInStock: 6,
        color: 'Red',
        size: 'M',
      },
    ],
  },
  // Non-Variant Product
  {
    name: 'Jerzees Long-Sleeve Heavyweight Blend T-Shirt',
    slug: toSlug('Jerzees Long-Sleeve Heavyweight Blend T-Shirt'),
    category: 'T-Shirts',
    images: ['/images/p12-1.jpg', '/images/p12-2.jpg', '/images/p12-3.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 23.78,
    listPrice: 0,
    brand: 'Jerzees',
    avgRating: 4.2,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 29,
    countInStock: 12,
    description:
      'Made with sustainably sourced USA grown cotton; Shoulder-to-shoulder tape; double-needle coverstitched front neck; Set-in sleeves; Rib cuffs with concealed seams; Seamless body for a wide printing area',
    size: '',
    color: '',
    reviews: [],
    variants: [],
  },
  // Another Product with Variants
  {
    name: "Jerzees Men's Long-Sleeve T-Shirt",
    slug: toSlug('Jerzees Men Long-Sleeve T-Shirt'),
    category: 'T-Shirts',
    brand: 'Jerzees',
    images: ['/images/p13-1.jpg', '/images/p13-2.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 13.86,
    listPrice: 16.03,
    avgRating: 4,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 55,
    countInStock: 0,
    description:
      'The Jerzees long sleeve t-shirt is made with dri-power technology that wicks away moisture to keep you cool and dry throughout your day. We also included a rib collar and cuffs for added durability, and a lay-flat collar for comfort.',
    size: '',
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'JLS-GRN-XL',
        images: ['/images/p13-1.jpg'],
        price: 13.86,
        countInStock: 8,
        color: 'Green',
        size: 'XL',
      },
      {
        sku: 'JLS-WHT-XXL',
        images: ['/images/p13-2.jpg'],
        price: 13.86,
        countInStock: 5,
        color: 'White',
        size: 'XXL',
      },
    ],
  },
  // Non-Variant Product
  {
    name: 'Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans',
    slug: toSlug('Silver Jeans Co. Mens Jace Slim Fit Bootcut Jeans'),
    category: 'Jeans',
    brand: 'Silver Jeans Co',
    images: ['/images/p21-1.jpg', '/images/p21-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 95.34,
    listPrice: 0,
    avgRating: 4.71,
    numReviews: 7,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 0 },
      { rating: 4, count: 2 },
      { rating: 5, count: 5 },
    ],
    countInStock: 54,
    numSales: 21,
    description:
      'Silver Jeans Co. Jace Slim Fit Bootcut Jeans - Consider Jace a modern cowboy jean. It sits below the waist and features a slim fit through the hip and thigh. Finished with an 18” bootcut leg opening that complements the slimmer silhouette while still fitting over boots',
    size: '',
    color: '',
    reviews: [],
    variants: [],
  },
  // Product with Variants
  {
    name: "ASICS Men's GT-2000 13 Running Shoes",
    slug: toSlug("ASICS Men's GT-2000 13 Running Shoes"),
    category: 'Shoes',
    brand: 'ASICS',
    images: ['/images/p45-1.jpg', '/images/p45-2.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 179.95,
    listPrice: 200,
    avgRating: 3.66,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 2 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    countInStock: 0,
    numSales: 64,
    description:
      "At least 50% of the shoe's main upper material is made with recycled content to reduce waste and carbon emissions",
    size: '',
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'ASICS-BLU-9',
        images: ['/images/p45-1.jpg'],
        price: 179.95,
        countInStock: 10,
        color: 'Blue',
        size: '9',
      },
      {
        sku: 'ASICS-BLK-10',
        images: ['/images/p45-2.jpg'],
        price: 179.95,
        countInStock: 12,
        color: 'Black',
        size: '10',
      },
    ],
  },
  {
    name: 'Puma Mens Long-Sleeve Training T-Shirt',
    slug: toSlug('Puma Mens Long-Sleeve Training T-Shirt'),
    category: 'T-Shirts',
    images: ['/images/p11-1.jpg', '/images/p11-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 19.99,
    listPrice: 25.99,
    brand: 'Puma',
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 4 },
      { rating: 5, count: 5 },
    ],
    numSales: 20,
    countInStock: 10,
    description:
      'Stay comfortable during your workouts with this long-sleeve training t-shirt made from breathable fabric.',
    size: '',
    color: '',
    reviews: [],
    variants: [],
  },
  {
    name: 'Under Armour Mens Charged Cotton Long Sleeve T-Shirt',
    slug: toSlug('Under Armour Mens Charged Cotton Long Sleeve T-Shirt'),
    category: 'T-Shirts',
    images: ['/images/p12-1.jpg', '/images/p12-2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 24.99,
    listPrice: 30.99,
    brand: 'Under Armour',
    avgRating: 4.3,
    numReviews: 15,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 0 },
      { rating: 3, count: 3 },
      { rating: 4, count: 5 },
      { rating: 5, count: 6 },
    ],
    numSales: 18,
    countInStock: 0, // Stock managed by variants
    description:
      'This t-shirt combines the softness of cotton with performance fabric for ultimate comfort.',
    size: '',
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'UA-TGRN-S',
        images: ['/images/p12-1.jpg'],
        price: 24.99,
        countInStock: 5,
        color: 'Green',
        size: 'S',
      },
      {
        sku: 'UA-TBLU-M',
        images: ['/images/p12-2.jpg'],
        price: 24.99,
        countInStock: 7,
        color: 'Blue',
        size: 'M',
      },
    ],
  },
  {
    name: 'Reebok Mens Graphic Tee',
    slug: toSlug('Reebok Mens Graphic Tee'),
    category: 'T-Shirts',
    images: ['/images/p13-1.jpg', '/images/p13-2.jpg'],
    tags: ['best-seller'],
    isPublished: true,
    price: 22.5,
    listPrice: 0,
    brand: 'Reebok',
    avgRating: 4.0,
    numReviews: 10,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 4 },
      { rating: 5, count: 2 },
    ],
    numSales: 12,
    countInStock: 8,
    description:
      'Show off your style with this comfortable and breathable graphic tee.',
    size: '',
    color: 'Black',
    reviews: [],
    variants: [],
  },
  {
    name: 'Adidas Mens Performance Tee',
    slug: toSlug('Adidas Mens Performance Tee'),
    category: 'T-Shirts',
    images: ['/images/p14-1.jpg', '/images/p14-2.jpg'],
    tags: ['todays-deal'],
    isPublished: true,
    price: 26.99,
    listPrice: 30.99,
    brand: 'Adidas',
    avgRating: 4.7,
    numReviews: 18,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 12 },
    ],
    numSales: 22,
    countInStock: 0,
    description:
      'The perfect blend of performance and comfort, ideal for your workout sessions.',
    size: '',
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'ADPT-WHT-L',
        images: ['/images/p14-1.jpg'],
        price: 26.99,
        countInStock: 10,
        color: 'White',
        size: 'L',
      },
      {
        sku: 'ADPT-GRY-XL',
        images: ['/images/p14-2.jpg'],
        price: 26.99,
        countInStock: 12,
        color: 'Grey',
        size: 'XL',
      },
    ],
  },
  {
    name: 'Nike Mens Dri-FIT T-Shirt',
    slug: toSlug('Nike Mens Dri-FIT T-Shirt'),
    category: 'T-Shirts',
    images: ['/images/p15-1.jpg', '/images/p15-2.jpg'],
    tags: ['new-arrival', 'featured'],
    isPublished: true,
    price: 30.0,
    listPrice: 35.0,
    brand: 'Nike',
    avgRating: 4.6,
    numReviews: 14,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 2 },
      { rating: 4, count: 6 },
      { rating: 5, count: 5 },
    ],
    numSales: 25,
    countInStock: 15,
    description:
      'Stay cool and dry with Nike Dri-FIT technology in this stylish and functional t-shirt.',
    size: '',
    color: 'Black',
    reviews: [],
    variants: [],
  },
  {
    name: 'Levis Mens Denim Jacket',
    slug: toSlug('Levis Mens Denim Jacket'),
    category: 'Jackets',
    images: ['/images/p16-1.jpg', '/images/p16-2.jpg'],
    tags: ['best-seller', 'todays-deal'],
    isPublished: true,
    price: 59.99,
    listPrice: 70.0,
    brand: "Levi's",
    avgRating: 4.3,
    numReviews: 16,
    ratingDistribution: [
      { rating: 1, count: 1 },
      { rating: 2, count: 1 },
      { rating: 3, count: 3 },
      { rating: 4, count: 5 },
      { rating: 5, count: 6 },
    ],
    numSales: 30,
    countInStock: 10,
    description: 'Classic Levi’s denim jacket, a timeless wardrobe essential.',
    size: '',
    color: 'Grey',
    reviews: [],
    variants: [],
  },
  {
    name: 'Hanes Mens ComfortBlend EcoSmart Sweatshirt',
    slug: toSlug('Hanes Mens ComfortBlend EcoSmart Sweatshirt'),
    category: 'Sweatshirts',
    images: ['/images/p11-1.jpg', '/images/p11-2.jpg'],
    tags: ['new-arrival'],
    isPublished: true,
    price: 18.99,
    listPrice: 20.99,
    brand: 'Hanes',
    avgRating: 4.5,
    numReviews: 11,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 1 },
      { rating: 3, count: 1 },
      { rating: 4, count: 5 },
      { rating: 5, count: 4 },
    ],
    numSales: 15,
    countInStock: 8,
    description:
      'Eco-friendly and ultra-comfortable sweatshirt perfect for everyday wear.',
    size: '',
    color: 'Green',
    reviews: [],
    variants: [],
  },
  {
    name: 'Adidas Mens Classic Hoodie',
    slug: toSlug('Adidas Mens Classic Hoodie'),
    category: 'Hoodies',
    images: ['/images/p12-1.jpg', '/images/p12-2.jpg'],
    tags: ['featured'],
    isPublished: true,
    price: 49.99,
    listPrice: 55.99,
    brand: 'Adidas',
    avgRating: 4.8,
    numReviews: 20,
    ratingDistribution: [
      { rating: 1, count: 0 },
      { rating: 2, count: 0 },
      { rating: 3, count: 1 },
      { rating: 4, count: 4 },
      { rating: 5, count: 15 },
    ],
    numSales: 30,
    countInStock: 0,
    description:
      'Adidas Classic Hoodie, perfect for workouts and casual outings.',
    size: '',
    color: '',
    reviews: [],
    variants: [
      {
        sku: 'ADCH-BLK-L',
        images: ['/images/p12-1.jpg'],
        price: 49.99,
        countInStock: 8,
        color: 'Black',
        size: 'L',
      },
      {
        sku: 'ADCH-WHT-M',
        images: ['/images/p12-2.jpg'],
        price: 49.99,
        countInStock: 7,
        color: 'White',
        size: 'M',
      },
    ],
  },
]

const reviews = [
  {
    rating: 1,
    title: 'Poor quality',
    comment:
      'Very disappointed. The item broke after just a few uses. Not worth the money.',
  },
  {
    rating: 2,
    title: 'Disappointed',
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: 'Needs improvement',
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: 'not bad',
    comment:
      'This product is decent, the quality is good but it could use some improvements in the details.',
  },
  {
    rating: 3,
    title: 'Okay, not great',
    comment:
      'It works, but not as well as I hoped. Quality is average and lacks some finishing.',
  },
  {
    rating: 3,
    title: 'Good product',
    comment:
      'This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.',
  },
  {
    rating: 4,
    title: 'Pretty good',
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: 'Very satisfied',
    comment:
      'Good product! High quality and worth the price. Would consider buying again.',
  },
  {
    rating: 4,
    title: 'Absolutely love it!',
    comment:
      'Perfect in every way! The quality, design, and comfort exceeded all my expectations.',
  },
  {
    rating: 4,
    title: 'Exceeded expectations!',
    comment:
      'Fantastic product! High quality, feels durable, and performs well. Highly recommend!',
  },
  {
    rating: 5,
    title: 'Perfect purchase!',
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: 'Highly recommend',
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: 'Just what I needed',
    comment:
      'Exactly as described! Quality exceeded my expectations, and it arrived quickly.',
  },
  {
    rating: 5,
    title: 'Excellent choice!',
    comment:
      'This product is outstanding! Everything about it feels top-notch, from material to functionality.',
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
]

const data: Data = {
  users,
  products,
  reviews,
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Featured Products',
      href: '/search?tag=featured',
    },
    {
      name: 'Best Sellers',
      href: '/search?tag=best-seller',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
    {
      title: 'Most Popular Shoes For Sale',
      buttonCaption: 'Shop Now',
      image: '/images/banner3.jpg',
      url: '/search?category=Shoes',
      isPublished: true,
    },
    {
      title: 'Best Sellers in T-Shirts',
      buttonCaption: 'Shop Now',
      image: '/images/banner1.jpg',
      url: '/search?category=T-Shirts',
      isPublished: true,
    },
    {
      title: 'Best Deals on Wrist Watches',
      buttonCaption: 'See More',
      image: '/images/banner2.jpg',
      url: '/search?category=Wrist Watches',
      isPublished: true,
    },
  ],
}

export default data
